backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
collections:
  - name: "songs"
    label: "Songs"
    folder: "/songs"
    create: true
    fields:
        - { label: "Title", name: "title", widget: "string"}
        - { label: "Body", name: "body", widget: "markdown"}
    - name: "services"
      label: "Services"
      folder: "/services"
      fields:
        - { label: "Date", name: "date", widget: "string"}
        - label: "Song List"
          name: "songList"
          widget: "list"
          field:
            - {label: "Song", name: "song", widget: "relation", collection: "songs", search_fields: ['name.title']}