backend:
  name: git-gateway
  branch: main
media_folder: public/img
public_folder: img
collections:
  - name: "songs"
    label: "Songs"
    folder: "/songs"
    create: true
    fields:
        - {label: "Title", name: "title", widget: "string"}
        - {label: "Body", name: "body", widget: "markdown"}
  - name: "services"
    label: "Services"
    folder: "/services"
    create: true
    fields:
      - {label: "Title", name: "title", widget: "datetime", format: "MMMM Do", date_format: "MMMM Do", time_format: false}
      - {label: "Date", name: "date", widget: "datetime", format: "MM-DD-YYYY", date_format: "MMMM Do", time_format: false}
      - label: "Songs"
        name: "songs"
        widget: "list"
        fields: 
          - label: "Song"
            name: "song"
            widget: "relation"
            collection: "songs"
            value_field: "{{slug}}"
            search_fields: ["title"]
            display_fields: ["title"]